// LUOGU_RID: 159969611
#include<bits/stdc++.h>
using namespace std;
const int maxn=2005;
int V=1002;
int dp[maxn][maxn];
string s,ans="";
bool fl=1;
void go(int i,int j)
{
    if(i<1)
    {
        return;
    }
    if(!dp[i][j+V])
    {
        fl=0;
        return;
    }
    if(s[i]=='?')
    {
        if(dp[i][j+V]==1)
        {
            ans='W'+ans;
            go(i-1,j+1);
        }
        else
        {
            if(dp[i][j+V]==2)
            {
                ans='D'+ans;
                go(i-1,j);
            }
            else
            {
                ans='L'+ans;
                go(i-1,j-1);
            }
        }
    }
    else
    {
        ans=s[i]+ans;
        if(s[i]=='W')
        {
            go(i-1,j+1);
        }
        else
        {
            if(s[i]=='D')
            {
                go(i-1,j);
            }
            else
            {
                go(i-1,j-1);
            }
        }
    }
}
int main()
{
    ios::sync_with_stdio(false),cin.tie(NULL),cout.tie(NULL);
    int n,k,i,j,d;
    cin>>n>>k>>s;
    s='*'+s;
    dp[0][V]=1;
    for(i=1;i<n;i++)
    {
        for(j=-k+1;j<k;j++)
        {
            if(s[i]=='?')
            {
                for(d=-1;d<=1;d++)
                {
                    if(abs(j-d)<k&&dp[i-1][j-d+V])
                    {
                        dp[i][j+V]=d+2;
                    }
                }
            }
            else
            {
                if(s[i]=='D')
                {
                    if(dp[i-1][j+V])
                    {
                        dp[i][j+V]=1;
                    }
                }
                else
                {
                    if(s[i]=='W')
                    {
                        if(abs(j+1)<k&&dp[i-1][j+1+V])
                        {
                            dp[i][j+V]=1;
                        }
                    }
                    else
                    {
                        if(abs(j-1)<k&&dp[i-1][j-1+V])
                        {
                            dp[i][j+V]=1;
                        }
                    }
                }
            }
        }
    }
    i=n;
    j=k;
    if(s[n]=='?')
    {
        for(d=-1;d<=1;d++)
        {
            if(abs(j-d)<k&&dp[i-1][j-d+V])
            {
                dp[i][j+V]=d+2;
            }
        }
    }
    else
    {
        if(s[n]=='W')
        {
            if(abs(j+1)<k&&dp[i-1][j+1+V])
            {
                dp[i][j+V]=1;
            }
        }
        else
        {
            if(abs(j-1)<k&&dp[i-1][j-1+V])
            {
                dp[i][j+V]=1;
            }
        }
    }
    go(n,k);
    if(fl)
    {
        cout<<ans<<endl;
        return 0;
    }
    i=n;
    j=-k;
    if(s[n]=='?')
    {
        for(d=-1;d<=1;d++)
        {
            if(abs(j-d)<k&&dp[i-1][j-d+V])
            {
                dp[i][j+V]=d+2;
            }
        }
    }
    else
    {
        if(s[n]=='W')
        {
            if(abs(j+1)<k&&dp[i-1][j+1+V])
            {
                dp[i][j+V]=1;
            }
        }
        else
        {
            if(abs(j-1)<k&&dp[i-1][j-1+V])
            {
                dp[i][j+V]=1;
            }
        }
    }
    fl=1;
    go(n,-k);
    if(fl)
    {
    	cout<<ans<<endl;
    	return 0;
	}
	cout<<"NO"<<endl;
    return 0;
}
