/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <bits/stdc++.h>

using namespace std;

class CTennisChampionship {
 public:
  void solve(std::istream &in, std::ostream &out) {
    long long n;
    in >> n;
    vector<long long> vll(1e5, 2e18);
    vll[1] = 2ll, vll[2] = 3ll;
    for (int i = 3; i < 1e5 && vll[i - 1] + vll[i - 2] <= 1e18; i++) {
      vll[i] = vll[i - 1] + vll[i - 2];
    }
    int ans = 1;
    for (int i = 1; vll[i] <= n; i++) {
      ans = i;
    }
    out << ans;
  }
};

int main() {
  CTennisChampionship solver;
  std::ios_base::sync_with_stdio(false);
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  in.tie(nullptr);
  out << std::fixed;
  out.precision(15);
  solver.solve(in, out);
  return 0;
}